name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    name: build on bun@latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run check
      - run: bun run build
