# NOTE: This workflow has been integrated into test-with-comment.yml
# You can disable or delete this file if you want all CI in one workflow
# Or keep it separate if you prefer modular workflows

name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - "**/*" # Do not run, since we have it all combined in ci-with-comment.yml

jobs:
  build:
    name: build on node@${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 22
          - 24

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run check
      - run: npm run build
