name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    name: build on node@${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 22
          - 24

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run check
      - run: npm run build

