name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  # schedule:
  #   - cron: 0 20 * * *

jobs:
  test:
    name: test on ${{ matrix.os-release }} node@${{ matrix.node-version }}
    runs-on: ${{ matrix.os-release }}

    strategy:
      matrix:
        node-version:
          - 22
          - 24
        os-release:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run test

  coverage:
    name: collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - run: npm ci

      - run: npm run test:unit
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit

      # - run: rm -rf coverage

      # - run: npm run test:integration
      # - uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     flags: integration

