name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  # schedule:
  #   - cron: 0 20 * * *

jobs:
  test:
    name: test on ${{ matrix.os-release }}
    runs-on: ${{ matrix.os-release }}

    strategy:
      matrix:
        os-release:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run test

  coverage:
    name: collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - run: bun run test:unit
      - uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit

      # - run: rm -rf coverage

      # - run: bun run test:integration
      # - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     flags: integration
